const data={seasoned20:{name:"조미구이재래김 5매×20봉",type:"조미김 · 넉넉한 구성",price:27000,image:"./products/seasoned-laver-20pack.jpg",desc:"바삭하게 구운 재래김을 5매씩 나눠 담은 대천우정김의 대표 구성입니다. 한 번에 꺼내 먹기 부담 없고, 온 가족의 아침 식사와 반찬으로 넉넉하게 즐기기 좋습니다.",features:["5매씩 간편하게 나눈 포장","가정 식탁에 넉넉한 20봉 구성","밥반찬·간식으로 즐기기 좋은 조미김"]},lunch24:{name:"도시락김 9절9매×24봉",type:"도시락김 · 한 끼 포장",price:12000,image:"./products/lunchbox-laver-24pack.jpg",desc:"밥 한 공기에 곁들이기 좋은 9절 도시락김입니다. 가방에 넣기 쉬운 소포장이라 학교, 직장, 여행지에서도 간편하게 고소한 맛을 즐길 수 있습니다.",features:["한 끼에 알맞은 9절 9매","보관과 휴대가 간편한 24봉","도시락·여행·간단한 식사에 추천"]},seasoned6:{name:"조미구이재래김 5매×6봉",type:"조미김 · 가벼운 구성",price:11000,image:"./products/seasoned-laver-6pack.jpg",desc:"대천우정김을 처음 맛보거나 가볍게 준비하고 싶은 분을 위한 6봉 구성입니다. 필요한 만큼만 꺼내 먹기 좋아 소가족이나 맛보기용으로 알맞습니다.",features:["부담 없이 고르는 6봉 구성","눅눅해지기 전에 즐기기 좋은 소포장","소가족·맛보기용으로 추천"]},gift4:{name:"조미구이재래김 10봉×4박스",type:"선물세트 · 대량 구성",price:60000,image:"./products/gift-set-4box.jpg",desc:"조미구이재래김 10봉이 든 박스 4개를 준비하는 넉넉한 구성입니다. 명절, 행사, 거래처와 가족을 위한 감사 선물로 활용하기 좋습니다.",features:["10봉 구성 4박스","명절·행사·단체 선물에 추천","배송 일정과 수량은 전화 상담 가능"]}};
const won=n=>`${n.toLocaleString("ko-KR")}원`,cart=new Map(),modal=document.querySelector(".modal"),drawer=document.querySelector(".drawer"),shade=document.querySelector(".shade"),toast=document.querySelector(".toast");let selected=null,timer;
function message(text){toast.textContent=text;toast.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove("show"),2100)}
function detail(id){const p=data[id];if(!p)return;selected=id;modal.querySelector("img").src=p.image;modal.querySelector("img").alt=p.name;modal.querySelector(".modal-copy>small").textContent=p.type;modal.querySelector("h2").textContent=p.name;modal.querySelector(".modal-copy>p").textContent=p.desc;modal.querySelector("ul").innerHTML=p.features.map(x=>`<li>${x}</li>`).join("");modal.querySelector(".price").textContent=won(p.price);modal.showModal()}
function add(id){const p=data[id];if(!p)return;cart.set(id,(cart.get(id)||0)+1);render();message(`${p.name}을(를) 데모 장바구니에 담았습니다.`)}
function render(){const count=[...cart.values()].reduce((a,b)=>a+b,0),total=[...cart].reduce((sum,[id,q])=>sum+data[id].price*q,0),list=document.querySelector(".cart-items");document.querySelector(".cart-open em").textContent=count;document.querySelector(".summary strong").textContent=won(total);if(!count){list.innerHTML='<div class="empty">담긴 제품이 없습니다.<br>대표 제품을 둘러보세요.</div>';return}list.innerHTML=[...cart].map(([id,q])=>{const p=data[id];return`<div class="cart-item"><img src="${p.image}" alt=""><div><b>${p.name}</b><small>${won(p.price)} · ${q}개</small></div><button data-remove="${id}">삭제</button></div>`}).join("");list.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{cart.delete(b.dataset.remove);render()})}
function openCart(){drawer.classList.add("open");drawer.setAttribute("aria-hidden","false");shade.hidden=false;document.body.classList.add("lock");document.querySelector(".drawer-x").focus()}
function closeCart(){drawer.classList.remove("open");drawer.setAttribute("aria-hidden","true");shade.hidden=true;document.body.classList.remove("lock")}
document.querySelectorAll(".card").forEach(card=>{const id=card.dataset.id;card.querySelector(".photo").onclick=()=>detail(id);card.querySelector(".add").onclick=()=>add(id)});document.querySelector(".x").onclick=()=>modal.close();document.querySelector(".modal-add").onclick=()=>selected&&add(selected);modal.onclick=e=>e.target===modal&&modal.close();document.querySelector(".cart-open").onclick=openCart;document.querySelector(".drawer-x").onclick=closeCart;shade.onclick=closeCart;document.addEventListener("keydown",e=>e.key==="Escape"&&drawer.classList.contains("open")&&closeCart());
const hamb=document.querySelector(".hamb"),nav=document.querySelector("nav");hamb.onclick=()=>{const open=nav.classList.toggle("open");hamb.setAttribute("aria-expanded",open)};nav.querySelectorAll("a").forEach(a=>a.onclick=()=>{nav.classList.remove("open");hamb.setAttribute("aria-expanded","false")});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add("show");observer.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll(".appear").forEach(x=>observer.observe(x));document.querySelector("#year").textContent=new Date().getFullYear();render();
